robot_teleoperation:
  ros__parameters:
    node_name: robot_teleoperation
    user_password: '156958'
    launch_order: ['3', '0', '1', '2', '4'] # Order: sensor, haptic, robot, effector, camera(launch correctly)
    hardware_device:
      haptic:
        name: hfd
        type: master
        port: /dev/ttyACM0
        title: MASTER-HFD
      robot:
        name: realman
        type: slave
        port: None # No virtual port
        title: SLAVE-REALMAN
      effector:
        name: ctek
        type: slave
        port: /dev/ttyUSB0
        title: SLAVE-CTEK
      sensor:
        name: xjcsensor
        type: slave
        port: /dev/ttyACM1
        title: SLAVE-XJCSENSOR
      camera:
        name: realsense
        type: slave
        port: None # No virtual port
        title: SLAVE-REALSENSE
